### ISSUE TITLE
Off by one error?

### ISSUE THREAD

**Issue by rtpHarry** [basarat/algorithms#5]
Shouldn't this be `array.length-1`?

https://github.com/basarat/algorithms/blob/0f973ba5ec6a82135b316a672250cf659ee410a4/src/shuffle/shuffle.ts#L10

I found this repo by this outdated gitbooks copy:

https://basarat.gitbooks.io/algorithms/content/docs/shuffling.html

but that one seems to work and this one introduces random empty items into the array.

**Comment by basarat** [comment]
> array.length-1

no. `randomInt` in this repo excludes the `before` :rose: : https://github.com/basarat/algorithms/blob/0f973ba5ec6a82135b316a672250cf659ee410a4/src/random/random.ts#L4
